---
- hosts: all
  gather_facts: no
  vars_files:
    - vault/vars.yml
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
  
  roles:
    #- initial
    - certbot
    - openconnect