- name: Restart ufw
  service:
    name: ufw
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart ocserv
  service:
    name: ocserv.service
    state: restarted
    