- name: Set desired port fact
  set_fact:
    configured_port: "{{ desired_ssh_port }}"

- name: Check if we're using initial port
  wait_for:
    port: "{{ initial_ssh_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: true
  register: default_ssh

- name: Set inventory ansible_port to default
  set_fact:
    ansible_port: "{{ initial_ssh_port }}"
  when: default_ssh is defined and
        default_ssh.state == "started"
  register: ssh_port_set

- name: Check if we're using the desired ssh port
  wait_for:
    port: "{{ desired_ssh_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: true
  register: configured_ssh
  when: default_ssh is defined and
        default_ssh.state is undefined

- name: Check is port configuration proper
  debug:
    msg: "SSH port is configured properly"
  when: configured_ssh is defined and
        configured_ssh.state is defined and
        configured_ssh.state == "started"
  register: ssh_port_set

- name: Fail if SSH port was not auto-detected (unknown)
  fail:
    msg: "The SSH port is neither {{ initial_ssh_port }} or {{ desired_ssh_port }}"
  when: ssh_port_set is undefined

- name: Allow {{ desired_ssh_port }}
  ufw:
    rule: allow
    port: {{ desired_ssh_port }}
    proto: tcp

- name: Setup {{ desired_ssh_port }} SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ configured_port }}"
  notify: "Restart sshd"

- name: Deny {{ initial_ssh_port }}
  ufw:
    rule: deny
    port: {{ initial_ssh_port }}
    proto: tcp
  notify: Restart ufw