- name: Ansible user creation
  user:
    name: ansible
    state: present
    groups: sudo
    append: true
    password: "{{ ansible_pass | password_hash('sha512') }}"

- name: Add ansible public key to host
  authorized_key:
    user: ansible
    key: "{{ ssh_public_key }}"
    state: present

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart sshd


- name: Allow SSH in UFW
  ufw: 
    rule: allow 
    port: "{{ ansible_port | default('22') }}"
    proto: tcp
  notify: Restart ufw

- name: Set firewall default policy
  ufw: 
    state: enabled
    policy: reject
  notify: Restart ufw