- name: Install squid
  apt:
    package: squid

- name: Generate squid config
  template:
    src: squid.conf.j2
    dest: "/etc/squid3/squid.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart squid